### ISSUE TITLE
cloudflare_page_rule keeps trying to recreate entries with upper case letters

### ISSUE THREAD

**Issue by jakubgs** [terraform-providers/terraform-provider-cloudflare#104]
```
% terraform version                                                                                               [08/09/18 12:54:50]
Terraform v0.11.7
+ provider.alicloud v1.10.0
+ provider.ansible v0.0.4
+ provider.cloudflare v1.1.0
+ provider.digitalocean v0.1.3
+ provider.google v1.16.2
```

Your `cloudflare_page_rule` keeps trying to recreate all entries that use `forwarding_url` which includes upper case letters because it seems to lowercase everything.

Example:
```
Terraform will perform the following actions:

  ~ module.redirect.cloudflare_page_rule.redirect[1]
      actions.0.forwarding_url.0.url: "https://some.service.com/abcde/" => "https://some.service.com/aBcDe/"
```

**Comment by patryk** [comment]
Hi, thanks for report. I have diagnosed the issue, and the problem is in our API code. Page Rule is saved (and works) correctly, but API returns value lowercased when serialized to JSON output. That's why Terraform thinks it needs to change.

I'll close issue here, but I have raised internal ticket and we'll fix the underlying cause with our API.

**Comment by jakubgs** [comment]
Thanks for looking into it, cheers!
