### ISSUE TITLE
cloudflare_record used with aws_acm_certificate always thinks it has to update

### ISSUE THREAD

**Issue by SpamapS** [terraform-providers/terraform-provider-cloudflare#154]
### Terraform Version
0.11.10

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_record
- aws_acm_certificate

### Terraform Configuration Files
```hcl
variable "domain" {}
variable "access_key" {}
variable "secret_key" {}
variable "cluster_region" {}
variable "cf_email" {}
variable "cf_token" {}
variable "subject" {}

provider "aws" {
  region     = "${var.cluster_region}"
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
}

provider "cloudflare" {
  email = "${var.cf_email}"
  token = "${var.cf_token}"
}

resource "aws_acm_certificate" "cert" {
  domain_name       = "${var.subject}"
  validation_method = "DNS"

  lifecycle {
    create_before_destroy = true
  }
}

resource "cloudflare_record" "validation" {
  domain = "${var.domain}"
  name   = "${aws_acm_certificate.cert.domain_validation_options.0.resource_record_name}"
  type   = "${aws_acm_certificate.cert.domain_validation_options.0.resource_record_type}"
  value  = "${aws_acm_certificate.cert.domain_validation_options.0.resource_record_value}"
}

resource "aws_acm_certificate_validation" "cert" {
  certificate_arn         = "${aws_acm_certificate.cert.arn}"
  validation_record_fqdns = ["${cloudflare_record.validation.hostname}"]
}

output "cert_arn" {
  value = "${aws_acm_certificate.cert.arn}"
}
```

### Debug Output
This has secret data in it, and is part of a much bigger configuration. If developers cannot reproduce then I can provide but redaction may take a long time.

### Panic Output
N/A

### Expected Behavior
Resource is already up to date, so I expect there to be no changes.

### Actual Behavior
No matter what, terraform completes successfully, but the next run always wants to add a single "." to the value, which is entirely unnecessary and is ignored by the API as equivalent.

```
  ~ module.zuul-cert.cloudflare_record.validation
      value: "_XXXXXXXXXX.yyyyyyyyyy.acm-validations.aws" => "_XXXXXXXXXX.yyyyyyyyyy.acm-validations.aws."
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by jacobbednarz** [comment]
👋 @SpamapS ! Thanks for the issue. This is sooo weird. One of our internal teams hit this exact thing yesterday 🙂 The issue is that the ACM DNS validation record returns the value with a trailing dot however the Cloudflare API trims it off. To fix this, you can call `replace` on the value to trim off the trailing period. Example:

```hcl 
resource "cloudflare_record" "validation" {
  domain = "${var.domain}"
  name   = "${aws_acm_certificate.cert.domain_validation_options.0.resource_record_name}"
  type   = "${aws_acm_certificate.cert.domain_validation_options.0.resource_record_type}"
  value  = "${replace(aws_acm_certificate.cert.domain_validation_options.0.resource_record_value}, "/[.]$/", "")}"
}
```

We could also add a `DiffSuppressFunc` to compare the values without the trailing period however seeing how Cloudflare trims it, I think that might hide some bad configuration instead of fixing it.

**Comment by SpamapS** [comment]
Thanks for the workaround!

I dug around in cloudflare's API docs and they don't seem to mention the equivalence of the dot and dotless values, but it does make some sense from a DNS perspective to just assume that a lack of a dot means "from the root of this domain". So to me, the DiffSuppressFunc is probably the right way to go, or in whatever does the value comparisons, an equivalance overload that chops any trailing dots off values would make sense.

**Comment by jacobbednarz** [comment]
Instead of suppressing the diff, perhaps we add validation to prevent
trailing periods? I hesitant to cover this up because there is quite a
difference in including and excluding the period in these values and that's
not something I think this tool should hide. Instead, I think we want to
align it to the API and how Cloudflare expects it to be formatted.
Essentially, leaving the decision to the internal Cloudflare systems
instead of third party tools.

WDYT?

**Comment by rohityadav225** [comment]
I am facing the same issue. what is the best course of action to fix this issue ?

**Comment by jacobbednarz** [comment]
@rohityadav225 you need to remove the trailing period in the value. Either using my `replace` solution from https://github.com/terraform-providers/terraform-provider-cloudflare/issues/154#issuecomment-439236237 or manually doing it yourself.

**Comment by rohityadav225** [comment]
I figured it out, what i needed is 
```
resource "cloudflare_record" "validation" {
  domain = "${var.domain}"
  name   = "${aws_acm_certificate.cert.domain_validation_options.0.resource_record_name}"
  type   = "${aws_acm_certificate.cert.domain_validation_options.0.resource_record_type}"
  value  = "${replace(aws_acm_certificate.cert.domain_validation_options.0.resource_record_value, "/[.]$/", "")}"
}
```

There was an extra `}`

**Comment by jleclanche** [comment]
@jacobbednarz After thinking about it for a bit, I'm of the opinion the module should treat this the same way that the terraform AWS module treats JSON canonicalization (which I believe it *does* do in some places due to similar issues with some AWS APIs).

**Comment by jacobbednarz** [comment]
@jleclanche I agree with the concept you've mentioned (same provider making things consistent across all products) but that isn't the same issue as what we have here. Here the issue is that one provider outputs a certain value and another provider that you're wanting to use expects it another way. As the trailing period does change the meaning of the value, I don't think the two values should be treated the same under the covers.

**Comment by jleclanche** [comment]
No I don't think that's correct. This issue happens to *manifest* because ACM is outputting DNS names with a trailing period, but it would show up regardless of the source.

Cloudflare doesn't "expect" the trailing dot to be present or not present -- it treats it the same way; as it should, because the DNS names are canonically the same. However what cloudflare *does* do is canonicalize the value into having no dot.

I'm arguing that the cloudflare provider should also canonicalize. The precedent for that is the AWS provider's JSON canonicalization. `{\n\t"foo": "bar"\n}` and `{"foo":"bar"}` are not the same string value, but they are the same JSON object and the AWS provider does canonicalize JSON in a few places where AWS does it as well, to prevent spurious updates.

**Comment by jacobbednarz** [comment]
> [...] it treats it the same way; as it should, because the DNS names are canonically the same.

I don't want to derail this discussion but that's the crux of the issue, they aren't canonically the same thing (one denotes an absolute domain whereas the other does not) and covering this up between DNS management systems can cause issues. The situation I want to avoid is where someone is relying on the AWS provider and the Cloudflare provider initially and then decides to change one part of that relationship only to find that their DNS records don't work anymore because the Cloudflare provider used to treat the two record values the same. This _has_ happened to us at least once while moving records around between providers (not Cloudflare, but another provider that did this exact thing) and it was a pain to track down.

> Cloudflare doesn't "expect" the trailing dot to be present or not present -- it treats it the same way; as it should, because the DNS names are canonically the same. However what cloudflare does do is canonicalize the value into having no dot.

Sure, perhaps expect was the wrong word to use here. My point was, the API only ever gives it to you one way, without the trailing period as that is what is used throughout the place. If you're managing that resource in code which relies on that value that comes back, you should really be matching it.

**Comment by jleclanche** [comment]
> The situation I want to avoid is where someone is relying on the AWS provider and the Cloudflare provider initially and then decides to change one part of that relationship only to find that their DNS records don't work anymore because the Cloudflare provider used to treat the two record values the same.

I'll concede the point if that is an actual possibility, but I don't see how it could happen right now.

**Comment by covracer** [comment]
First of all, thanks for all of the coding, testing, documentation, dealing with people like me, and other work that brought us here, and all that will follow. I really appreciate being able to intergrate Cloudflare API interactions with other infrastructure interactions.

## Impact
I consider Terraform's change detection to be one of its most useful features. I'm sad to see it broken in this particular instance, when there is a trailing period / dot in `cloudflare_record.value`. How this bug affected me is that when I saw `terraform apply && terraform plan` showing differences, I:
1. Had to perform an intraline diff
2. Had to figure out how to refer to the punctuation mark in a way that my search engine understood
3. Had to find this closed bug report
4. Had to replace what had looked like a simpler, working value, when I first ran `terraform apply`, with the more complex workaround discussed here

I interpret a goal of provider interoperability from @jacobbednarz 's comments above, which is awesome. Perhaps contrary to that, I interpret the subtlety of this problem, and the effort required of authors to debug and fix it, as an indication that interoperability between different providers cannot be assumed. I can't help but question whether the real root cause of my problem was trying to venture beyond a single-provider combination of resources.

## Cloudflare API
> I think we want to align [the Terraform provider] to the API and how Cloudflare expects [value/content] to be formatted. Essentially, leaving the decision to the internal Cloudflare systems[...]

> Ideally, I'd expect end users to be aware of this difference and account for it in their resources.

What expectations does the Cloudflare API have, and how should someone using the Terraform provider learn about them? What I've been able to find in the [Cloudflare API documentation](https://api.cloudflare.com/#dns-records-for-a-zone-properties), is that for a CNAME Record, `content` ([where `cloudflare_record.value` goes](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_record.go#L304)) must be "A valid hostname". I can see how that might mean a short name, rather than a fully-qualified-down-to-the-trailing-dot one, but it's not super clear to me. If anyone has links or clarification, I'd appreciate that. I don't see any mention in the notes or elsewhere that `content` may be modified by the server such that `POST(content=c); assert GET().content == c` could fail. I am surprised by that behavior.

> [example.com. and example.com] aren't canonically the same thing (one denotes an absolute domain whereas the other does not)

Is there anything in the response from the Cloudflare API that indicates whether a CNAME is relative or absolute? (If so, maybe the provider could fix up the raw response with a `.` period / dot?) If the API provides no mechanism for telling a CNAME of `example.com.` apart from a CNAME of `example.com`, then I would infer that the decision of the API and internal Cloudflare systems is that they are equivalent.

## Where to do What

> [...]leav[e] the decision to the internal Cloudflare systems[...]

Are you saying that the internal systems should be able to change their decision in the future, without users needing to upgrade their Terraform provider? How precedented or hypothetical would such a change be? In my opinion, both diff-suppression and validation approaches to fixing this issue are instances of the Terraform provider making the decision, rather than delegating the decision to the internal Cloudflare systems. I agree that the Terraform provider is probably not the ideal place to establish a different standard than the API and internal Cloudflare systems. Maybe a linter could be an alternative mechanism for ensuring best practices for broad compatibility (that I understand @jacobbednarz to be advocating)?

> The situation I want to avoid is where someone is relying on the AWS provider and the Cloudflare provider initially and then decides to change one part of that relationship only to find that their DNS records don't work anymore because the Cloudflare provider used to treat the two record values the same. This has happened to us at least once while moving records around between providers (not Cloudflare, but another provider that did this exact thing) and it was a pain to track down.

How did the maintainers of that provider handle your bug report? Is there anything we can learn from their approach? Without specifics, I'm afraid none of us can help double check that it was in fact the exact same thing. If your issue affects multiple providers, could a multi-provider solution (like a linter) more effectively prevent that trouble than independent measures in just the Cloudflare provider?

## Diff Suppression
This seems like the most user-friendly approach to me.

## Validation
> Instead of suppressing the diff, perhaps we add validation to prevent trailing periods?

I think informative validation, so that failures happen early, and for an obvious reason, would be a helpfully fix change detection. I see this:

https://github.com/cloudflare/terraform-provider-cloudflare/blob/d8fe659584c76d896bcf95dcf3e1f2ffbf5cb5b0/cloudflare/resource_cloudflare_record.go#L344-L347

(Differently than the function name and error message would lead me to believe) it seems like [validateRecordName](https://github.com/cloudflare/terraform-provider-cloudflare/blob/d8fe659584c76d896bcf95dcf3e1f2ffbf5cb5b0/cloudflare/validators.go#L34-L59) is validating `content`/`value`. Would the validation approach be as easy as inserting something like following?
```go
	case "CNAME":
		if strings.HasSuffix(value, ".") {
			return fmt.Errorf("Alias value in CNAME record must be relative (no trailing period), got: %q", value)
		}
```

Or would it be better to set a `ValidateFunc` in the `Schema`, [like type has](
https://github.com/cloudflare/terraform-provider-cloudflare/blob/d8fe659584c76d896bcf95dcf3e1f2ffbf5cb5b0/cloudflare/resource_cloudflare_record.go#L49-L54)? Maybe something like:
```go
			"value": {
				Type:          schema.TypeString,
				Optional:      true,
				Computed:      true,
				ConflictsWith: []string{"data"},
				ValidateFunc: validation.StringDoesNotMatch(regexp.MustCompile(`\.$`), ""),
			},
```

## Workaround
It seems to me like a couple things have changed since the issue was first raised. `trimsuffix(dot_suffixed_string, ".")` ([documentation](https://www.terraform.io/docs/configuration/functions/trimsuffix.html), [changelog](https://github.com/hashicorp/terraform/blob/v0.12/CHANGELOG.md#01217-december-02-2019)) is now available as a more concise way to preemptively reformat the written `value` match what will be read back. There's also now the set type to deal with in `aws_acm_certificate`. So here's how I ended up achieving interoperability between registry.terraform.io/hashicorp/aws 3.22.0 and registry.terraform.io/cloudflare/cloudflare 2.15.0:
```json
    "cloudflare_record": {
      "my-record": {
        "name": "${tolist(aws_acm_certificate.my-certificate.domain_validation_options)[0].resource_record_name}",
        "provider": "cloudflare.cloudflare",
        "type": "${tolist(aws_acm_certificate.my-certificate.domain_validation_options)[0].resource_record_type}",
        "value": "${trimsuffix(tolist(aws_acm_certificate.my-certificate.domain_validation_options)[0].resource_record_value, \".\")}",
        "zone_id": "ae36f999674d196762efcc5abb06b345"
      }
    }
```
(Please pardon my JSON syntax. I'm currently experimenting with [terraformpy](https://github.com/NerdWalletOSS/terraformpy).)

**Comment by jacobbednarz** [comment]
Thanks for a great write up @covracer. It's always good to see longer form comments on a platform that is often drive by commenters, I appreciate it!

> Perhaps contrary to that, I interpret the subtlety of this problem, and the effort required of authors/users to debug and fix it, as an indication that interoperability between different providers cannot be assumed.

I don't personally think it's either explicitly assumed or not assumed. (My) goal with this provider has been to ensure it's agnostic and mindful of potential integrations and pitfalls. This comes from my experience on both sides of this fence as both an individual where I had total control of integrations and how I chose to interact with them versus working for a company where the requirements were stricter or contractually bound. 

> [...] I can see how that might mean a short name, rather than a fully-qualified-down-to-the-trailing-dot one, but it's not super clear to me. If anyone has links or clarification, I'd appreciate that. 

I unfortunately don't have any better resources for this other than my own experiences. Within most of Cloudflare's systems, it will have access to the context of the DNS record in question and using internal logic, not require the relative/canonical definition explicitly.  

> I don't see any mention in the notes or elsewhere that content may be modified by the server such that POST(content=c); assert GET().content == c could fail. I am surprised by that behavior.

I'm sorry, I don't quite follow exactly what you mean here but do you mean, what we send to the API should match what Terraform has? If so, the issue is larger than the Cloudflare API; it's also Terraform state management whereby we define that the API data should match what is on disk.

> If the API provides no mechanism for telling a CNAME of example.com. apart from a CNAME of example.com, then I would infer that the decision of the API and internal Cloudflare systems is that they are equivalent.

I've covered this up a little further but to reiterate, this is part of the issue. The Terraform provider **is not making the decision** of the importance of the trailing period but it is a differing of the input of the external value to what Cloudflare says it is. Here, the AWS value has a trailing period, Terraform sends that trailing period, Cloudflare doesn't need it so it doesn't return it in the value, Terraform provider is intended to keep the remote Cloudflare API in sync with what is on disk, so it differs from what the input initially was.

> Are you saying that the internal systems should be able to change their decision in the future, without users needing to upgrade their Terraform provider? How precedented or hypothetical would such a change be?

Not quite. I'm saying that if a user inputs a value whereby a trailing character has importance in some scenarios, the provider shouldn't be reasonable for determining whether to hide it or not. The onus is on the end user to understand that system interaction. 

A few examples that I've come across or had to help debug:

- [Hashicorp's very own DNS provider](https://registry.terraform.io/providers/hashicorp/dns/latest) which . See various resources for the usage.
- ACME/Let's Encrypt integrations
- Other DNS/edge providers where technologies like BIND or authoritative DNS is used

The issues that popped up were that these providers expected the values with canonical references (as they were only DNS providers without the concept of an account or zone similar to Cloudflare) and without it, they assume that the value is a sub zone within the configuration. This is a case where provider interaction and normalising didn't work well and the prime examples of what I'm aiming to avoid here.

> How did the maintainers of that provider handle your bug report? Is there anything we can learn from their approach? Without specifics, I'm afraid none of us can help double check that it was in fact the exact same thing. 

It wasn't a bug 😃 It is how their systems were designed to work and due to normalisation between providers, it was dropped. Again, the provider was attempting to make decisions on the end user's behalf and they end user was none the wiser.

> If your issue affects multiple providers, could a multi-provider solution (like a linter) more effectively prevent that trouble than independent measures in just the Cloudflare provider?

You're welcome to look at something like this but I don't have the need to spend time on it. 

> Diff Suppression
> This seems like the most user-friendly approach to me.

Until you have to debug it 😉 Suppression of any kind makes debugging far more difficult than it needs to be so we try to avoid it where possible unless there is a mismatch in the representation of Terraform and the remote API.

> Or would it be better to set a `ValidateFunc` in the Schema, like type has? Maybe something like:

I'd be on board with using validation instead because that gives you the ability to clearly articulate how this provider expects it and it has to be a conscious decision from the end user to resolve. I didn't explore that path any further due to the lack of interest in it as a solution. I suspect because with validation, it still involves removing the trailing period either programmatically or by manually copy/pasting the value in.

> It seems to me like a couple things have changed since the issue was first raised. trimsuffix(dot_suffixed_string, ".") (documentation, changelog) is now available as a more concise way to preemptively reformat the written value to match what will be read back. 

Nice pick up! It's always good to see hacky solutions get better with time 😄 It definitely wasn't around when we were playing with this internally so I'm glad to see it land in Terraform core.

**Comment by ricardo-allium** [comment]
For anyone landing here in the provider v5 era: this exact behavior still exists in v5 (`cloudflare_dns_record`), and it's not limited to AWS ACM — any upstream that emits DNS-standard FQDNs with a trailing dot triggers it. In our case it was Google Certificate Manager: `google_certificate_manager_dns_authorization.x.dns_resource_record[0].name/.data` both include the trailing dot, the Cloudflare API strips it on write, and every subsequent plan shows a perpetual in-place update on `name` and `content`:

```
~ content = "....certificatemanager.goog" -> "....certificatemanager.goog."
~ name    = "_acme-challenge_xxx.example.com" -> "_acme-challenge_xxx.example.com."
```

Verified on v5.17.0 and v5.23.0 — the dns_record normalization fixes that shipped between those versions don't cover trailing-dot equivalence of `name`/`content`.

The workaround in the comment above still works; the modern spelling is `trimsuffix`:

```hcl
resource "cloudflare_dns_record" "validation" {
  zone_id = var.zone_id
  name    = trimsuffix(google_certificate_manager_dns_authorization.x.dns_resource_record[0].name, ".")
  type    = "CNAME"
  content = trimsuffix(google_certificate_manager_dns_authorization.x.dns_resource_record[0].data, ".")
  ttl     = 60
  proxied = false
}
```

That took our plan from 16 perpetual changes to 0. It would be nice if the provider treated `foo.example.com.` and `foo.example.com` as semantically equal during plan, the way it already normalizes several other dns_record attributes.
