### ISSUE TITLE
Feature request: add secrets support to Cloudflare Workers resource

### ISSUE THREAD

**Issue by tomtaylor** [terraform-providers/terraform-provider-cloudflare#164]
This is a feature request to support [Cloudflare Worker secrets](https://developers.cloudflare.com/workers/api/resource-bindings/secrets-vault/) in the `cloudflare_worker_script` resource

### Terraform Version
`Terraform v0.11.10`

### Affected Resource(s)
- cloudflare_worker_script

### Terraform Configuration Files

I'd like to be able to define:

```terraform
resource "cloudflare_worker_script" "worker" {
  zone    = "${var.zone}"
  content = "${file("../dist/bundle.js")}"
  secrets = "${file("secrets.js")}"
}
```

And for that to set the JS file that defines the secrets as per [the documentation](https://developers.cloudflare.com/workers/api/resource-bindings/secrets-vault/).

**Comment by jacobbednarz** [comment]
Apologies for the radio silence on this one @tomtaylor. I thought I dropped a note in here explaining why I've purposely left it but it seems not 😞 I initially had reservations about this as there wasn't an easy and secure way of storing this data and maintaining it without unnecessary updates all the time. But, I think I have a solution.

The schema for this new field will need to implement a custom [`DiffSuppressFunc`](https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#diffsuppressfunc) which instead of looking at the contents and storing that value, will instead sha256/sha512 the contents, compare it against the stored checksum and then work out if it needs to make changes. This way we are only storing the checksum and the while will be computed everytime, it will only initiate API calls when the checksums change. Also, no need for storing plaintext secrets. 😄 

I'll take a pass at this sometime this week and see how it goes.

**Comment by jacobbednarz** [comment]
Side note, secrets support will also need to be added to the upstream [`cloudflare-go`](https://github.com/cloudflare/cloudflare-go) library to use it here.

**Comment by jbergknoff** [comment]
Any further thoughts/plans on this?

**Comment by jacobbednarz** [comment]
Not from me. We haven't needed this internally yet so my focus has been elsewhere. Feel free to take a pass at it if you'd like support.

**Comment by blakeembrey** [comment]
Is this feature request similar to `secret_text` being uploaded with https://github.com/cloudflare/serverless-cloudflare-workers/blob/e95e1e9c9770ed9a3d9480c1fa73e64391268354/shared/multiscript.js#L76-L80? I'd love to contribute help to getting `secret_text` bindings supported, right now I'm using Terraform to write a JSON file into the package before I bundle it with `wrangler` to upload variables (because the variables come from Terraform).
