### ISSUE TITLE
Missing documentation for User Agent blocking

### ISSUE THREAD

**Issue by Workshop2** [terraform-providers/terraform-provider-cloudflare#220]
### Terraform Version
v0.11.11

### Affected Resource(s)
User Agent

### Expected Behavior
I am unable to find any documentation as to how to use User Agent Blocking in this provider, however, I can see the code exists: 
https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/vendor/github.com/cloudflare/cloudflare-go/user_agent.go

**Comment by jacobbednarz** [comment]
The code your seeing is actually from the upstream `cloudflare-go` library (which underpins all the functionality here) not the Terraform provider. There isn't support for User Agent blocking however you can achieve it with the Filter based Firewall Rules.

```hcl
resource "cloudflare_filter" "my_ua" {
  zone_id = "d41d8cd98f00b204e9800998ecf8427e"
  description = "User agent I want to block"
  expression = "(http.user_agent eq \"bad ua\")"
}

resource "cloudflare_firewall_rule" "block_bad_ua" {
  zone_id = "d41d8cd98f00b204e9800998ecf8427e"
  description = "Block my_ua"
  filter_id = "${cloudflare_filter.my_ua.id}"
  action = "block"
}
```

I'm not sure of the Cloudflare roadmap but personally, we've migrated most of our rules to the Filter  based Firewall due to the flexibility and extensibility it allows. I'm open to adding the user agent blocking resource though if there is still demand for it.

**Comment by Workshop2** [comment]
Ah, sorry about the confusion. I will give these a go. Many thanks

**Comment by jacobbednarz** [comment]
As I mentioned, if there is still a demand for using User Agent blocking (i.e. can't/won't migrate at the moment) I'm happy to entertain a new resource. If you want it, open a new issue with the new resource issue template and we can work through it there 😃
