### ISSUE TITLE
Still can't manage Page Rules with custom cache key

### ISSUE THREAD

**Issue by mphoratiu** [terraform-providers/terraform-provider-cloudflare#365]
This could be a regression of the https://github.com/terraform-providers/terraform-provider-cloudflare/issues/117 issue.

### Versions
$ terraform -version
Terraform v0.11.14
+ provider.cloudflare v1.15.0

### This is what I have done:
- I have a  non-terraform created page rule with a custom cache key set by support
- I've imported it in the terraform setup we already have (containing everything else that was already there)
- added one more rule that we needed.
- I've run a plan and apply, got an error like:
```
cloudflare_page_rule.rule-name: Failed to update Cloudflare Page Rule: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1004,\"message\":\"Page Rule validation failed: See messages for details.\"}],\"messages\":[{\"code\":1,\"message\":\".settings[1]: 'cache_key' is read only and can not be modified or added\",\"type\":null},{\"code\":2,\"message\":\".settings[1].value: This value should not be blank.\",\"type\":null}],\"result\":null}"
```

Was anything changed recently that would cause this?

I couldn't reopen https://github.com/terraform-providers/terraform-provider-cloudflare/issues/117 (reason for creating new issue).

**Comment by jacobbednarz** [comment]
Heya,

This is due to the change in #338 where we swapped from using the PATCH endpoint to the PUT endpoint which entirely replaces the rule. The PR outlines why this decision was made but the tl;dr is that using the PATCH endpoint was more problematic for more use cases than using the PUT endpoint. Neither are perfect but this is the less broken way.

I'm still trying to work with the folks at Cloudflare on finding a better solution here but we haven't made any progress as of late.
