### ISSUE TITLE
Imprecise documentation for provider initialization

### ISSUE THREAD

**Issue by jakubgs** [terraform-providers/terraform-provider-cloudflare#570]
According to your documentation:

>`account_id` - (Optional) Configure API client with this account ID, so calls use the account API rather than the (default) user API. __This is required for other users in your account to have access to the resources you manage.__
>https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/website/docs/index.html.markdown

I encountered in issue in which creation of [load_balancer_monitor](https://www.terraform.io/docs/providers/cloudflare/r/load_balancer_monitor.html) failed with:
```
Quota exceeded. You are currently allowed 0 monitors. Please re-use or delete any unused monitors.
```
Because my `account_id` was not set.

I'd recommend re-wording that section to be something like:
>This is required for other users in your account to have access to the resources you manage, as well as to correctly apply resource limits.

Also, this makes this setting even less optional. I'd just call it required to make it simpler for users.

**Comment by jacobbednarz** [comment]
The `account_id` key could be documented better however your proposal still doesn't quite outline what it's actually used for. The actual use is whenever you're attempting to manage [account level](https://api.cloudflare.com/#account-load-balancer-pools-properties) resources instead of the [zone](https://api.cloudflare.com/#load-balancers-properties) or even user based resources. [`account_id` is used somewhat as a flag](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/provider.go#L190) for the configuration system on which endpoint to use based on the provided information. Older products are the only ones with this differentiation as now everything is either zone or account and isn't accessible in both types.

Your underlying issue was that you were attempting to manage the wrong type of resources. Rule of thumb, if you're managing things across your (paid) account, you probably want to set `account_id` otherwise it should be omitted.

**Comment by jakubgs** [comment]
>Rule of thumb, if you're managing things across your (paid) account, you probably want to set account_id otherwise it should be omitted.

Sounds to me like that "rule of thumb" should be included in the documentation.
