### ISSUE TITLE
Why does updating a Custom SSL public/private keys ForceNew?

### ISSUE THREAD

**Issue by joel-g** [terraform-providers/terraform-provider-cloudflare#622]
See: https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_custom_ssl.go#L51

Why does updating the public and private key (like after a cert renewal or adding a SAN) force a destroy and create? Why doesn't the provider use the PATCH API?

Destroy and create is a dangerous operation on production applications. Should the create fail for any reason we are left in a state with no SSL certificate.

**Comment by jacobbednarz** [comment]
I can't speak for this resource specifically but other certificate resources don't lend themselves very well to in-place replacement due to a number of reasons hidden outside of Terraform (hostname verification, alexa top 1000 restrictions, rotation timeouts). We've actually moved away from managing certificates in Terraform due to the update APIs not always working in our favour or having sane failure modes.

If you'd like to remove the `ForceNew`, I'd recommend you confirm that the manual API calls work as you expect with some testing and then look at removing it from the schema and confirm the current test cases all pass. The functionality for updating in-place is already there so we shouldn't need any additional functionality if it works without it.

**Comment by joel-g** [comment]
Thanks @jacobbednarz. I will fork and do some testing.

**Comment by jacobbednarz** [comment]
Closing as there isn't anything to action here. Feel free to open a PR or another issue with the specifics of your findings if this is something you wish to pursue.
