### ISSUE TITLE
Wrong cloudflare_access_policy.include.okta.identity_provider_id key

### ISSUE THREAD

**Issue by analytically** [terraform-providers/terraform-provider-cloudflare#640]
When using the newly added (provider version 2.5) `cloudflare_access_policy.include.okta` I'm getting the following:

`Error: error creating Access Policy for ID "": error from makeRequest: HTTP status 400: content "{\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"code\": 11017,\n      \"message\": \"access.api.error.invalid_policy\"\n    }\n  ],\n  \"messages\": []\n}\n"`

When debugging, the CloudFlare UI uses `connection_id` instead of `identity_provider_id` (as in the docs).

![image](https://user-images.githubusercontent.com/254434/77955703-08257980-72a7-11ea-8c4c-7e99c16c963e.png)

**Comment by jacobbednarz** [comment]
Have raised 1860059 with Cloudflare to have this confirmed.

**Comment by jacobbednarz** [comment]
The advice from Cloudflare on this one:

> In my test both fields are correct and yields the same Access policy. I would suggest following the fields stated in our documentation in your API request.

With regards to your invalid policy, this was something I ran into trying to setup the integration tests it's quite broad. To use Okta, you need to have the provider setup (for realsy) and then add the Access Group configuration otherwise you end up with an invalid policy.

**Comment by analytically** [comment]
That's exactly what I'm doing:

![image](https://user-images.githubusercontent.com/254434/78028627-afe98880-7335-11ea-9e5b-cd85fee09ed1.png)

**Comment by analytically** [comment]
That's what I'm doing but it doesn't work:

![image](https://user-images.githubusercontent.com/254434/78028747-d7d8ec00-7335-11ea-9ef9-041faeb602cc.png)

**Comment by analytically** [comment]
No, even with having an Access Group it doesn't work:

```
  on main.tf line 65, in resource "cloudflare_access_group" "okta_everyone":
  65:     okta {

Blocks of type "okta" are not expected here.
```

**Comment by analytically** [comment]
There is no test demonstrating the include.okta/github/azure work. I believe there's a bug in the provider.

**Comment by analytically** [comment]
And using the policy directly without a group doesn't work either:

![image](https://user-images.githubusercontent.com/254434/78030108-f8a24100-7337-11ea-8539-838c27baa183.png)

**Comment by jacobbednarz** [comment]
> There is no test demonstrating the include.okta/github/azure work

There was however it was removed due to being too hard to maintain https://github.com/terraform-providers/terraform-provider-cloudflare/commit/4865352f3d4ff495dd9285eeb2a1f23803db8bb9. It requires the real identity provider to be connected to Cloudflare which doesn’t lend itself to automation as is. GSuite and GitHub were both manually tested while developing this so can confirm they are OK but they use identical code so they should all work. 

Instead of posting screenshots, are you are to provide a full test case outline exactly what you’re doing and how you’re attempting to use this? I’d recommend you start with the GitHub provider and work from there to get a working policy and then swap out Okta.

**Comment by analytically** [comment]
I have a working policy (email), it's just the Okta stuff that doesn't work.

**Comment by analytically** [comment]
Found the issue, typo 'Otka' (both present in this provider and the CloudFlare docs)

**Comment by jacobbednarz** [comment]
Thanks, I'll take a look at fixing this in `cloudflare-go`.

**Comment by analytically** [comment]
When setting the policy from Terraform (using identity_provider_id) results in the UI getting confused (seemingly only matching connection_id when set from the UI before).
