### ISSUE TITLE
Unable to import load balancer pools and monitors

### ISSUE THREAD

**Issue by pranj** [terraform-providers/terraform-provider-cloudflare#70]
Hello,

I'm attempting to import some existing organization wide load balancer pools and monitors. I've gone ahead and fetched the appropriate ids using the Cloudflare api.

I successfully made requests to the following api endpoints in order to get the ids.
https://api.cloudflare.com/client/v4/organizations/<organization_id>/load_balancers/monitors
https://api.cloudflare.com/client/v4/organizations/<organization_id>/load_balancers/pools

The [importing state documentation](https://developers.cloudflare.com/terraform/advanced-topics/importing-state/) doesn't contain any examples on how to import organization wide resources but I would assume that the correct approach here is just to disregard the zone name.

My attempts to import these resources looked like this:
`terraform import cloudflare_load_balancer_monitor.<name> <id>`

Unfortunately, I'm provided with the following error if I try this:
```
* import cloudflare_load_balancer_monitor.healthy result: <id>: import cloudflare_load_balancer_monitor.<name> (id: <id>): Terraform detected a resource with this ID doesn't
exist. Please verify the ID is correct. You cannot import non-existent
resources using Terraform import.
```

I've double checked that I'm using the correct ids for the resources. Is the import functionality supported for these resources? If so, what is the correct approach here?

Note that I've been able to successfully import other zone specific resources like records and page rules just fine.

I've also attempted to create new load balancer pool resources but have had my efforts blocked because of issue #54 

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- cloudflare_load_balancer_monitor
- cloudflare_load_balancer_pool

**Comment by SteveGoldthorpe-Work** [comment]
I'm doing that now and is working fine for me.
The magic seems to be setting the org in your provider file, I do the following:

    provider "cloudflare" {
      use_org_from_zone = "<one of my domain names>"
    }

This seems to be enough to use my organisation rather than user resources.

Import of a pool
`cli4 organizations/:<my org name>/load_balancers/pools`
add a relevant pool entry
`terraform import cloudflare_load_balancer_pool.<pool name> <id>`

Import of a load-balancer
`cli4 zones/:<domain name>/load_balancers`
add a relevant load balancer entry
`terraform import cloudflare_load_balancer.<lb name> <domain name>/<id>`

The bit I didn't get straight away was that load-balancers should reference pools directly rather than hard coding ids:

    resource "cloudflare_load_balancer" "<lb name>" {
      zone             = "${var.domain}"
      name             = "<name>.${var.domain}"
      default_pool_ids = ["${cloudflare_load_balancer_pool.<pool name>.id}"]
      fallback_pool_id = "${cloudflare_load_balancer_pool.<pool name>.id}"
      proxied          = true
    }

Hope this helps.

**Comment by pranj** [comment]
Thanks @SteveGoldthorpe-Work, setting the org in the provider file did the trick!
