### ISSUE TITLE
Add support for new IdP features in Cloudflare Access

### ISSUE THREAD

**Issue by xens** [terraform-providers/terraform-provider-cloudflare#719]
New features have been added to Cloudflare Access / Cloudflare for Teams recently (https://blog.cloudflare.com/releasing-cloudflare-access-most-requested-feature). It allows companies with multiple IdPs to select to which IdPs they want to connect their Access applications, and also bypass the IdP selection if only one is selected.

Goal of this issue is to track the implementation of this missing features inside the Cloudflare Terraform provider. For now these features are not yet supported inside the cloudflare-go library (WIP -> https://github.com/cloudflare/cloudflare-go/issues/483). When it'll be done we'll be able to work on the Terraform provider implementation.

**Comment by xens** [comment]
@jacobbednarz I don't know if you're familiar with the cloudflare-go release strategy ? I saw that it happens ~every 2-4 weeks ? And then when it'll be merged + released when we'll be able to import the new library inside this repo (I don't know who does that / what's the process) ? Just for me to understand when I have a chance to start to work on that one :)

**Comment by jacobbednarz** [comment]
Are you able to please create a single issue for each feature missing instead of a giant issue? Not all feature implementations are equal and some will be dependant on factors outside of our control and I wouldn't like to hold them all up because of one or not being able to use inbuilt functionality like [GitHub closing keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to manage the issue state.

Regarding `cloudflare-go`, it follows a similar release cycle to this provider. It's done on an as-is basis which usually happens every couple of weeks to a month (as you noted).

**Comment by xens** [comment]
Yes that makes sense, I've opened respectively #720 and #721 for now. Closing this one.
