### ISSUE TITLE
@ dns record name forces replacement

### ISSUE THREAD

**Issue by james64** [terraform-providers/terraform-provider-cloudflare#735]
### Terraform Version
I am running `v0.12.26` which is not the latest (`v0.12.28`) but it is the latest my distro has in repos right now. Let's see if you can reproduce my issue anyway.

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_record

### Terraform Configuration Files
```hcl
provider "cloudflare" {}

resource "cloudflare_zone" "sme_sk" {
  zone = "sme.sk"
}

resource "cloudflare_record" "cname" {
  name = "@"
  type = "CNAME"
  value = "cname.com"
  zone_id = cloudflare_zone.sme_sk.id
}
```

### Debug Output
[gist link](https://gist.github.com/james64/ac180fdf5ed35e158ff2d52d2009eed0)

### Panic Output
no panic

### Expected Behavior
Infrastructure should be up-to date according to `terraform plan`. See steps to reproduce below.

### Actual Behavior
Actual plan on output:
```
  # cloudflare_record.cname must be replaced
-/+ resource "cloudflare_record" "cname" {
      ~ created_on  = "2020-07-14T10:28:23.720897Z" -> (known after apply)
      - data        = {} -> null
      ~ hostname    = "sme.sk" -> (known after apply)
      ~ id          = "83ca501654d3351efd6186e581faa3c4" -> (known after apply)
      ~ metadata    = {
          - "auto_added"             = "false"
          - "managed_by_apps"        = "false"
          - "managed_by_argo_tunnel" = "false"
          - "source"                 = "primary"
        } -> (known after apply)
      ~ modified_on = "2020-07-14T10:28:23.720897Z" -> (known after apply)
      ~ name        = "sme.sk" -> "@" # forces replacement
      - priority    = 0 -> null
      ~ proxiable   = true -> (known after apply)
      ~ proxied     = true -> false
      ~ ttl         = 1 -> (known after apply)
        type        = "CNAME"
        value       = "cname.com"
        zone_id     = "fc00ad844299af2912e9686b04c49a02"
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce
1. Manually create domain zone
1. Manually create CNAME record with `@` as name and `cname.com` as value
1. `terraform import` created zone
1. `terraform import` created cname record
1. Run `terraform plan`

I feel like this should produce empty plan because both terraform code and manually created and imported record has `@` as name.

Please let me know whether you can reproduce this. Thanks!

**Comment by jacobbednarz** [comment]
The issue here is that if you create it in the UI, the value from the API differs to what Terraform has and it wants to perform an update to get it back in sync. The change itself is a noop however because the API values differ, it still wants to do it.

If you create the record with `name = "@"` (without importing) the value doesn't flap and will remain that way.

The cause of the issue here is having a different `Import` `name` value (from the API) to what you're defining in the resource. If you do it the other way, it's handled as expected. I'm not sure if we want to handle the translation between the two as it hasn't been a big enough issue and I suspect it may introduce some state management challenges.
